### PR TITLE
Candle abstraction

### LINKED ISSUE #10: Possible abstraction for class Candle
Hello and thanks for this awesome library!

I might have a suggestion that could help me better integrate this library into my application. It seems that most if not all indicators depend somehow on class Candle or delegate mapper to select proper values.

Hower when dealing with large collections I have to convert my data objects to Candles which creates a lot of unnecessary allocations. It would be better if I could loosely depend on this libary by using some interface like this:

```
public interface IOhlcData
{
    DateTime DateTime { get; }

    decimal Open { get; }

    decimal High { get; }

    decimal Low { get; }

    decimal Close { get; }
}
```

I would then just implement it and use my own business objects without much or any modifications.
Thanks for considering and if you find it suitable I think I can create a pull request with such modification.

### PR DESCRIPTION
**Pull request by LadislavBohm**
I created abstraction of Candle and IndexedCandle class using interfaces IOhlcvData and IIndexedOhlcvData. Mostly done using Resharper's refactoring techniques. The amount of changes is quite large, but consist mostly of substitution of specific class for interfaces.

What I am not so sure about two things:

1. Naming of the two new interfaces. Instead of IOhlcvData it could be just IOhlcv and IIndexedOhlcv respectively. 
2. Another shadowing in IIndexedOhlcvData. There already was shadowing using in generic version of IIndexedObject so I used it too to make it compatible with rest of the code. Would like to hear your ideas about it.

Fixes #10

### CODE REVIEW

**Comment by lppkarl** [comment]
@LadislavBohm First, thank you for your PR, you're quite fast with that 👍 

For the naming, I agree with using the name IOhlcv instead of the longer name IOhlcvData. The IIndexedObject is mainly targeted for IOhlcv object, using IIndexedOhlcv is also reasonable & I also agree with that.

**Comment by lppkarl** [comment]
@LadislavBohm I've just resolved the conflicts & merged it to v3.1 branch (the branch that i'm developing for new features & bugfixes for the next release), you may switch to that branch as well 😄

**Comment by LadislavBohm** [comment]
Thanks, I wanted to take a look at the conflicts and possibly rename those interfaces this weekend. You did the hard work of resolving the conflicts so now renaming can be as simple as two refactoring commands 😃

**Comment by lppkarl** [comment]
@LadislavBohm I have renamed those classes 😄 Thanks for all your contribution 👍

**Pull request merged**
