### PR TITLE
VWAP indicator with 4 passing unit tests

### PR DESCRIPTION
**Pull request by codebeaulieu**
Master was merged into VWAP prior to creating unit tests.

### CODE REVIEW

**Comment by lppkarl** [comment]
@codebeaulieu thanks for the PR. but I've double checked the fail log, it seems the TestVwap_CloseIsBelowVwapAsync test case is not working, is that okay on your local system?

**Comment by codebeaulieu** [comment]
Interesting. Wonder why it would work on my system and not yours. Something to do with DateTime perhaps. 

I'll look into this tonight. Thanks @lppkarl.

**Comment by codebeaulieu** [comment]
@Ippkarl Hey sorry for the delay, I pushed an update to the tests that include a time zone.

**Comment by codebeaulieu** [comment]
FYI, I've put this new VWAP indicator to use against live market data and it is spot on. Testing against both SPY and QQQ on the 5 minute scale.

**Comment by kiranmaya** [comment]
This works good, why it is included?

**Pull request merged**
